#include <bits/stdc++.h>
using namespace std;

#include "Tree.hpp"
#include "A star.hpp"
#include "failureTree.hpp"
#include "stride.hpp"
#include "XXYY.hpp"
#include "23.hpp"
#include "38.hpp"
#include "39.hpp"
#include "40.hpp"
#include "41.hpp"
#include "42.hpp"
#include "43.hpp"
#include "44.hpp"
#include "45.hpp"
#include "46.hpp"
#include "47.hpp"
#include "48.hpp"
#include "49.hpp"
#include "50.hpp"
#include "51.hpp"
#include "52.hpp"
#include "53.hpp"
#include "54.hpp"
#include "59.hpp"
#include "60.hpp"
#include "98.hpp"
