# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  CodeForces_config = debug

else ifeq ($(config),release)
  CodeForces_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := CodeForces

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CodeForces:
ifneq (,$(CodeForces_config))
	@echo "==== Building CodeForces ($(CodeForces_config)) ===="
	@${MAKE} --no-print-directory -C . -f CodeForces.make config=$(CodeForces_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f CodeForces.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CodeForces"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"